import { ParfumeEntity } from "@/entities/parfume/model/parfume";

export const perfumes: ParfumeEntity[] = [
  {
    id: "550e8400-e29b-41d4-a716-446655440000",
    slug: "amouage-interlude-for-men",
    title: "Amouage Interlude For Men",
    brand: "Amouage",
    price: [11000, 20000],
    ml: [5, 10],
    season: "winter",
    gender: "male",
    description:
      "Amouage Interlude For Men — это насыщенный древесно-пряный аромат с нотами ладана, амбры и кожи. Он создаёт атмосферу загадочности и глубины, идеально подходит для холодного времени года.",
    img: "/assets/img/perfume/Amouage_Interlude_For_Men.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440001",
    slug: "boadicea-blue-sapphire",
    title: "Boadicea the Victorious Blue Sapphire",
    brand: "Boadicea the Victorious",
    price: [23000, 42000],
    ml: [5, 10],
    season: "fall",
    gender: "unisex",
    description:
      "Boadicea Blue Sapphire — это благородный и элегантный аромат, сочетающий в себе фруктовые, цветочные и древесные ноты. Его теплая база делает его идеальным выбором для осеннего сезона.",
    img: "/assets/img/perfume/Boadicea_the_Victorious_Blue_Sapphire.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440002",
    slug: "amouage-reflection-45",
    title: "Amouage Reflection 45",
    brand: "Amouage",
    price: [15000, 27000],
    ml: [5, 10],
    season: "spring",
    gender: "male",
    description:
      "Amouage Reflection 45 — это более насыщенная версия классического Reflection Man. Он раскрывается сложными и многослойными нотами, идеально подходящими для весенних дней.",
    img: "/assets/img/perfume/Amouage_Reflection_45.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440003",
    slug: "arte-olfatto-black-hashish",
    title: "Arte Olfatto Black Hashish",
    brand: "Arte Olfatto",
    price: [4400, 7920],
    ml: [5, 10],
    season: "winter",
    gender: "male",
    description:
      "Black Hashish — это тёплый, дымный аромат с нотами ладана, древесных смол и специй. Его глубокий, насыщенный характер делает его идеальным для зимы.",
    img: "/assets/img/perfume/Arte_Olfatto_Black_Hashish.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440004",
    slug: "bdk-gris-charnel-extrait",
    title: "BDK Parfums Gris Charnel Extrait",
    brand: "BDK Parfums",
    price: [9350, 16830],
    ml: [5, 10],
    season: "fall",
    gender: "unisex",
    description:
      "Gris Charnel Extrait — это насыщенная версия оригинального аромата с глубокими древесными и пряными нотами, подчёркивающими утонченность осеннего сезона.",
    img: "/assets/img/perfume/BDK_Parfums_Gris_Charnel_Extrait.jpg",
  },
  // {
  //   id: "550e8400-e29b-41d4-a716-446655440005",
  //   slug: "bdk-oud-abramad",
  //   title: "BDK Parfums Oud Abramad",
  //   brand: "BDK Parfums",
  //   price: [6000, 10800],
  //   ml: [5, 10],
  //   season: "winter",
  //   gender: "male",
  //   description:
  //     "Oud Abramad — это богатый и тёмный удовый аромат с нотами кожи, специй и амбры. Его сложная композиция идеально подходит для холодной зимы.",
  //   img: "/assets/img/perfume/BDK_Parfums_Oud_Abramad.jpg",
  // },
  {
    id: "550e8400-e29b-41d4-a716-446655440006",
    slug: "boadicea-bodacious",
    title: "Boadicea the Victorious Bodacious",
    brand: "Boadicea the Victorious",
    price: [13000, 23400],
    ml: [5, 10],
    season: "spring",
    gender: "female",
    description:
      "Bodacious — это дерзкий и энергичный аромат, наполненный фруктовыми и цветочными нотами с тёплыми пряными оттенками, идеально подходящий для весеннего сезона.",
    img: "/assets/img/perfume/Boadicea_the_Victorious_Bodacious.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440007",
    slug: "boadicea-dragon",
    title: "Boadicea the Victorious Dragon",
    brand: "Boadicea the Victorious",
    price: [44000, 79200],
    ml: [5, 10],
    season: "winter",
    gender: "unisex",
    description:
      "Dragon — мощный и харизматичный аромат с сочетанием восточных, древесных и цветочных нот, символизирующий силу и энергию.",
    img: "/assets/img/perfume/Boadicea_the_Victorious_Dragon.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440008",
    slug: "boadicea-hasu",
    title: "Boadicea the Victorious Hasu",
    brand: "Boadicea the Victorious",
    price: [44000, 79200],
    ml: [5, 10],
    season: "summer",
    gender: "unisex",
    description:
      "Hasu — свежий и лёгкий аромат с нотами цитрусовых и зелёных аккордов, создающий ощущение лёгкости и утончённости в летний период.",
    img: "/assets/img/perfume/Boadicea_the_Victorious_Hasu.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440009",
    slug: "boadicea-valiant",
    title: "Boadicea the Victorious Valiant",
    brand: "Boadicea the Victorious",
    price: [35000, 63000],
    ml: [5, 10],
    season: "fall",
    gender: "unisex",
    description:
      "Valiant — это аромат роскоши и элегантности, с нотами цитрусовых, ириса и древесины, которые идеально раскрываются в прохладные осенние дни.",
    img: "/assets/img/perfume/Boadicea_the_Victorious_Valiant.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440010",
    slug: "bvlgari-kobraa",
    title: "BVLGARI Kobraa",
    brand: "BVLGARI",
    price: [17050, 30690],
    ml: [5, 10],
    season: "fall",
    gender: "male",
    description:
      "BVLGARI Kobraa — это мистический аромат с нотами ладана, герани и древесины, придающий уверенность и харизму. Подходит для осеннего времени года.",
    img: "/assets/img/perfume/BVLGARI_Kobraa.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440011",
    slug: "bvlgari-orom",
    title: "BVLGARI Orom",
    brand: "BVLGARI",
    price: [18000, 32400],
    ml: [5, 10],
    season: "summer",
    gender: "male",
    description:
      "BVLGARI Orom — это солнечный, свежий и энергичный аромат с цитрусовыми и древесными нотами, создающий ощущение роскоши и свободы.",
    img: "/assets/img/perfume/BVLGARI_Orom.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440012",
    slug: "chanel-sycomore",
    title: "Chanel Sycomore",
    brand: "Chanel",
    price: [15000, 27000],
    ml: [5, 10],
    season: "fall",
    gender: "unisex",
    description:
      "Chanel Sycomore — это благородный древесный аромат с дымными и землистыми оттенками, олицетворяющий элегантность и утонченность.",
    img: "/assets/img/perfume/Chanel_Sycomore.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440013",
    slug: "christian-louboutin-loubicharme",
    title: "Christian Louboutin Loubicharme",
    brand: "Christian Louboutin",
    price: [12000, 21600],
    ml: [5, 10],
    season: "spring",
    gender: "female",
    description:
      "Loubicharme — это чарующий цветочный аромат с утонченными древесными и мускусными акцентами, подчёркивающий женственность и чувственность.",
    img: "/assets/img/perfume/Christian_Louboutin_Loubicharme.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440014",
    slug: "clive-christian-hedonistic",
    title: "Clive Christian Hedonistic JUMP UP AND KISS ME",
    brand: "Clive Christian",
    price: [33000, 59400],
    ml: [5, 10],
    season: "winter",
    gender: "unisex",
    description:
      "Clive Christian Hedonistic — это роскошный восточно-пряный аромат с оттенками шафрана, жасмина и ванили, который согревает и окутывает уютом.",
    img: "/assets/img/perfume/Clive_Christian_Hedonistic_JUMP_UP_AND_KISS_ME.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440015",
    slug: "clive-christian-matsukita",
    title: "Clive Christian Matsukita",
    brand: "Clive Christian",
    price: [30000, 54000],
    ml: [5, 10],
    season: "fall",
    gender: "unisex",
    description:
      "Matsukita — это элегантный восточный аромат с нотами цитрусов, бергамота, специй и древесины, создающий таинственную и манящую ауру.",
    img: "/assets/img/perfume/Clive_Christian_Matsukita.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440016",
    slug: "clive-christian-x-masculine",
    title: "Clive Christian X Masculine",
    brand: "Clive Christian",
    price: [20000, 36000],
    ml: [5, 10],
    season: "winter",
    gender: "male",
    description:
      "Clive Christian X Masculine — это мощный аромат с пряными и древесными нотами, создающий уверенный, благородный и загадочный образ.",
    img: "/assets/img/perfume/Clive_Christian_X_Masculine.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440017",
    slug: "creed-absolu-aventus",
    title: "Creed Absolu Aventus",
    brand: "Creed",
    price: [23000, 41400],
    ml: [5, 10],
    season: "summer",
    gender: "male",
    description:
      "Absolu Aventus — это более насыщенная версия легендарного Aventus, в которой усилены древесные и фруктовые ноты, создавая незабываемую свежесть.",
    img: "/assets/img/perfume/Creed_Absolu_Aventus.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440018",
    slug: "creed-aventus",
    title: "Creed Aventus",
    brand: "Creed",
    price: [14000, 25200],
    ml: [5, 10],
    season: "spring",
    gender: "male",
    description:
      "Aventus — культовый аромат с нотами ананаса, чёрной смородины, бергамота и мускуса, воплощающий силу, успех и стиль.",
    img: "/assets/img/perfume/Creed_Aventus.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440019",
    slug: "creed-centaurus",
    title: "Creed Centaurus",
    brand: "Creed",
    price: [17000, 30600],
    ml: [5, 10],
    season: "fall",
    gender: "unisex",
    description:
      "Centaurus — это гармония древесных, фруктовых и амбровых нот, создающая аристократический и утончённый образ.",
    img: "/assets/img/perfume/Creed_Centaurus.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440020",
    slug: "creed-delphinus",
    title: "Creed Delphinus",
    brand: "Creed",
    price: [17000, 30600],
    ml: [5, 10],
    season: "spring",
    gender: "unisex",
    description:
      "Creed Delphinus — это свежий, фруктово-древесный аромат с нотами цитрусовых, зелени и мускуса, идеально подходящий для весны.",
    img: "/assets/img/perfume/Creed_Delphinus.jpg",
  },
  // {
  //   id: "550e8400-e29b-41d4-a716-446655440021",
  //   slug: "creed-royal-oud",
  //   title: "Creed Royal Oud",
  //   brand: "Creed",
  //   price: [15000, 27000],
  //   ml: [5, 10],
  //   season: "fall",
  //   gender: "unisex",
  //   description:
  //     "Creed Royal Oud — это роскошный восточный аромат с древесными и пряными нотами, создающий элегантный и благородный образ.",
  //   img: "/assets/img/perfume/Creed_Royal_Oud.jpg",
  // },
  {
    id: "550e8400-e29b-41d4-a716-446655440022",
    slug: "dior-ambre-nuit",
    title: "Dior Ambre Nuit",
    brand: "Dior",
    price: [9000, 16200],
    ml: [5, 10],
    season: "fall",
    gender: "unisex",
    description:
      "Dior Ambre Nuit — это теплый и утонченный амбровый аромат с нотами розы, специй и древесины, идеально подходящий для осени.",
    img: "/assets/img/perfume/Dior_Ambre_Nuit.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440023",
    slug: "dior-oud-ispahan",
    title: "Dior Oud Ispahan",
    brand: "Dior",
    price: [11000, 19800],
    ml: [5, 10],
    season: "winter",
    gender: "unisex",
    description:
      "Dior Oud Ispahan — это богатый, глубокий восточный аромат с нотами уда, розы и смол, создающий загадочную атмосферу.",
    img: "/assets/img/perfume/Dior_Oud_Ispahan.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440024",
    slug: "essential-parfums-bois-imperial",
    title: "Essential Parfums Bois Imperial",
    brand: "Essential Parfums",
    price: [7500, 13500],
    ml: [5, 10],
    season: "summer",
    gender: "unisex",
    description:
      "Bois Imperial — это свежий и яркий древесный аромат с нотами ветивера, пачули и специй, идеальный для летнего времени года.",
    img: "/assets/img/perfume/Essential_Parfums_Bois_Imperial.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440025",
    slug: "essential-parfums-orange-x-santal",
    title: "Essential Parfums Orange X Santal",
    brand: "Essential Parfums",
    price: [7500, 13500],
    ml: [5, 10],
    season: "spring",
    gender: "unisex",
    description:
      "Orange X Santal — это утонченный и теплый аромат с яркими цитрусовыми и древесными нотами, идеально раскрывающийся весной.",
    img: "/assets/img/perfume/Essential_Parfums_Orange_X_Santal.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440027",
    slug: "ex-nihilo-outcast-blue",
    title: "Ex Nihilo Outcast Blue Extrait",
    brand: "Ex Nihilo",
    price: [18000, 32400],
    ml: [5, 10],
    season: "fall",
    gender: "male",
    description:
      "Outcast Blue Extrait — это смелый и дерзкий аромат с насыщенными древесными и пряными нотами, идеально подходящий для осеннего времени года.",
    img: "/assets/img/perfume/Ex_Nihilo_Outcast_Blue_Extrait_de_Parfum.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440028",
    slug: "fort-and-manle-fatih-sultan-mehmed",
    title: "Fort & Manle Fatih Sultan Mehmed",
    brand: "Fort & Manle",
    price: [14000, 25200],
    ml: [5, 10],
    season: "spring",
    gender: "unisex",
    description:
      "Fatih Sultan Mehmed — это богатый восточный аромат с нотами розы, специй и древесины, создающий атмосферу величия и роскоши.",
    img: "/assets/img/perfume/Fort_and_Manle_Fatih_Sultan_Mehmed.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440029",
    slug: "fort-and-manle-v-for-vetiver",
    title: "Fort & Manle V for Vetiver",
    brand: "Fort & Manle",
    price: [12000, 21600],
    ml: [5, 10],
    season: "summer",
    gender: "male",
    description:
      "V for Vetiver — это освежающий и элегантный аромат с акцентом на ветивер, цитрусы и древесные ноты, создающий чувство свободы и легкости.",
    img: "/assets/img/perfume/Fort_and_Manle_V_for_vetiver.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440030",
    slug: "fragrance-du-bois-cannabis-intense",
    title: "Fragrance du Bois Cannabis Intense",
    brand: "Fragrance du Bois",
    price: [19500, 35100],
    ml: [5, 10],
    season: "fall",
    gender: "unisex",
    description:
      "Cannabis Intense — это богатый древесно-пряный аромат с оттенками конопли, табака и тёплых специй, создающий уютную атмосферу осени.",
    img: "/assets/img/perfume/Fragrance_du_Bois_Cannabis_Intense.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440031",
    slug: "franck-boclet-cocaine",
    title: "Franck Boclet Cocaine",
    brand: "Franck Boclet",
    price: [10000, 18000],
    ml: [5, 10],
    season: "winter",
    gender: "unisex",
    description:
      "Cocaine — это гипнотический и страстный аромат с нотами табака, ванили и белых цветов, создающий роскошное звучание на зимний период.",
    img: "/assets/img/perfume/Franck_Boclet_Cocaine.jpg",
  },
  // {
  //   id: "550e8400-e29b-41d4-a716-446655440032",
  //   slug: "frederic-malle-the-moon",
  //   title: "Frederic Malle The Moon",
  //   brand: "Frederic Malle",
  //   price: [25000, 45000],
  //   ml: [5, 10],
  //   season: "fall",
  //   gender: "unisex",
  //   description:
  //     "The Moon — это загадочный и завораживающий восточный аромат с акцентом на розу, уда и малину, раскрывающийся особенно красиво в прохладные осенние вечера.",
  //   img: "/assets/img/perfume/Frederic_Malle_The_Moon.jpg",
  // },
  {
    id: "550e8400-e29b-41d4-a716-446655440033",
    slug: "frederic-malle-the-night",
    title: "Frederic Malle The Night",
    brand: "Frederic Malle",
    price: [45000, 81000],
    ml: [5, 10],
    season: "winter",
    gender: "male",
    description:
      "The Night — это насыщенный удовый аромат с тёмными древесными нотами, розой и амброй, идеально подходящий для холодного времени года.",
    img: "/assets/img/perfume/Frederic_Malle_The_Night.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440034",
    slug: "gucci-the-voice-of-the-snake",
    title: "Gucci The Voice of the Snake",
    brand: "Gucci",
    price: [13500, 24300],
    ml: [5, 10],
    season: "fall",
    gender: "unisex",
    description:
      "The Voice of the Snake — это загадочный и мистический аромат с нотами уда, пачули и специй, создающий гипнотическое звучание осени.",
    img: "/assets/img/perfume/Gucci_The_Voice_Of_The_Snake.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440035",
    slug: "initio-musk-therapy",
    title: "INITIO Musk Therapy",
    brand: "INITIO",
    price: [15500, 27900],
    ml: [5, 10],
    season: "spring",
    gender: "unisex",
    description:
      "Musk Therapy — это утонченный, нежный и расслабляющий аромат с мускусными и цитрусовыми нотами, идеально подходящий для весны.",
    img: "/assets/img/perfume/INITIO_Musk_Therapy.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440036",
    slug: "initio-oud-for-greatness",
    title: "INITIO Oud for Greatness",
    brand: "INITIO",
    price: [19500, 35100],
    ml: [5, 10],
    season: "winter",
    gender: "unisex",
    description:
      "Oud for Greatness — это величественный и благородный аромат с удом, специями и лавандой, создающий мощное и запоминающееся звучание.",
    img: "/assets/img/perfume/INITIO_Oud_For_Greatness.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440037",
    slug: "initio-oud-for-happiness",
    title: "INITIO Oud for Happiness",
    brand: "INITIO",
    price: [18500, 33300],
    ml: [5, 10],
    season: "fall",
    gender: "unisex",
    description:
      "Oud for Happiness — это современный, древесно-цитрусовый аромат с нотами ванили, уда и специй, создающий тёплое и радостное настроение осени.",
    img: "/assets/img/perfume/INITIO_Oud_For_Happiness.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440038",
    slug: "initio-paragon",
    title: "INITIO Paragon",
    brand: "INITIO",
    price: [16500, 29700],
    ml: [5, 10],
    season: "spring",
    gender: "unisex",
    description:
      "Paragon — это уникальный аромат с нотами лаванды, шалфея, перца и сандала, создающий атмосферу комфорта и гармонии.",
    img: "/assets/img/perfume/INITIO_Paragon.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440039",
    slug: "initio-rehab",
    title: "INITIO Parfums Prives Rehab",
    brand: "INITIO",
    price: [14000, 25200],
    ml: [5, 10],
    season: "fall",
    gender: "unisex",
    description:
      "Rehab — это изысканный древесно-пряный аромат с нотами лаванды, ванили и древесины, создающий уютное и теплое ощущение осени.",
    img: "/assets/img/perfume/INITIO_Parfums_Prives_Rehab.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440040",
    slug: "initio-side-effect",
    title: "INITIO Parfums Prives Side Effect",
    brand: "INITIO",
    price: [17500, 31500],
    ml: [5, 10],
    season: "winter",
    gender: "unisex",
    description:
      "Side Effect — это глубокий и страстный аромат с нотами рома, ванили, корицы и табака, создающий чувственное и роскошное звучание.",
    img: "/assets/img/perfume/Initio_Parfums_Prives_Side_Effect.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440041",
    slug: "kilian-dark-lord",
    title: "Kilian Dark Lord",
    brand: "Kilian",
    price: [21000, 37800],
    ml: [5, 10],
    season: "fall",
    gender: "male",
    description:
      "Dark Lord — это мощный, мистический аромат с нотами рома, кожи, ветивера и специй, создающий элегантную и загадочную ауру.",
    img: "/assets/img/perfume/Kilian_Dark_Lord.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440042",
    slug: "kilian-musk-oud",
    title: "Kilian Musk Oud",
    brand: "Kilian",
    price: [19500, 35100],
    ml: [5, 10],
    season: "winter",
    gender: "unisex",
    description:
      "Musk Oud — это богатый восточный аромат с сочетанием уда, мускуса и розы, создающий чувственное и величественное звучание.",
    img: "/assets/img/perfume/Kilian_Musk_Oud.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440043",
    slug: "kilian-smoking-hot",
    title: "Kilian Smoking Hot",
    brand: "Kilian",
    price: [18000, 32400],
    ml: [5, 10],
    season: "fall",
    gender: "unisex",
    description:
      "Smoking Hot — это теплый, загадочный аромат с нотами корицы, табака и ванили, создающий атмосферу уюта и соблазнительности.",
    img: "/assets/img/perfume/Kilian_Smoking_Hot.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440044",
    slug: "kilian-straight-to-heaven",
    title: "Kilian Straight to Heaven White Cristal",
    brand: "Kilian",
    price: [19000, 34200],
    ml: [5, 10],
    season: "summer",
    gender: "male",
    description:
      "Straight to Heaven — это свежий и бодрящий аромат с нотами рома, мускуса и древесины, создающий элегантный и расслабляющий эффект.",
    img: "/assets/img/perfume/Kilian_Straight_to_Heaven_White_Cristal.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440045",
    slug: "kilian-vodka-on-the-rocks",
    title: "Kilian Vodka on the Rocks",
    brand: "Kilian",
    price: [17500, 31500],
    ml: [5, 10],
    season: "summer",
    gender: "unisex",
    description:
      "Vodka on the Rocks — это освежающий, прохладный аромат с нотами кориандра, розы и кардамона, идеально подходящий для жарких летних дней.",
    img: "/assets/img/perfume/Kilian_Vodka_on_the_Rocks.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440046",
    slug: "louis-vuitton-lovers",
    title: "Louis Vuitton Lovers",
    brand: "Louis Vuitton",
    price: [23000, 41400],
    ml: [5, 10],
    season: "spring",
    gender: "unisex",
    description:
      "Lovers — это романтичный и легкий аромат с цветочными и мускусными нотами, создающий нежное и утонченное звучание весной.",
    img: "/assets/img/perfume/Louis_Vuitton_Lovers.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440047",
    slug: "louis-vuitton-matiere-noir",
    title: "Louis Vuitton Matière Noire",
    brand: "Louis Vuitton",
    price: [21000, 37800],
    ml: [5, 10],
    season: "fall",
    gender: "unisex",
    description:
      "Matière Noire — это загадочный и глубокий аромат с акцентом на уда, пачули и черную смородину, создающий богатую и соблазнительную композицию.",
    img: "/assets/img/perfume/Louis_Vuitton_Matiere_Noir.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440048",
    slug: "louis-vuitton-nuit-de-feu",
    title: "Louis Vuitton Nuit de Feu",
    brand: "Louis Vuitton",
    price: [25000, 45000],
    ml: [5, 10],
    season: "winter",
    gender: "unisex",
    description:
      "Nuit de Feu — это мощный, дымный и пряный аромат с акцентом на ладан и амбру, создающий загадочную и мистическую атмосферу.",
    img: "/assets/img/perfume/Louis_Vuitton_Nuit_de_Feu.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440049",
    slug: "louis-vuitton-ombre-nomade",
    title: "Louis Vuitton Ombre Nomade",
    brand: "Louis Vuitton",
    price: [27000, 48600],
    ml: [5, 10],
    season: "winter",
    gender: "unisex",
    description:
      "Ombre Nomade — это насыщенный и выразительный аромат с доминирующим удом, который идеально раскрывается в холодную погоду.",
    img: "/assets/img/perfume/Louis_Vuitton_Ombre_Nomade.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440050",
    slug: "maison-crivelli-oud-maracuja",
    title: "Maison Crivelli Oud Maracuja",
    brand: "Maison Crivelli",
    price: [19500, 35100],
    ml: [5, 10],
    season: "fall",
    gender: "unisex",
    description:
      "Oud Maracuja — это необычное сочетание уда и маракуйи, создающее контрастный, сладко-древесный аромат, идеально подходящий для осени.",
    img: "/assets/img/perfume/Maison_Crivelli_Oud_Maracuja.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440051",
    slug: "maison-francis-kurkdjian-baccarat-rouge-540",
    title: "Maison Francis Kurkdjian Baccarat Rouge 540",
    brand: "Maison Francis Kurkdjian",
    price: [18000, 32400],
    ml: [5, 10],
    season: "fall",
    gender: "unisex",
    description:
      "Baccarat Rouge 540 — это легендарный аромат с кристально-сладкими нотами шафрана, жасмина и амбры, создающий неповторимое звучание.",
    img: "/assets/img/perfume/Maison_Francis_Kurkdjian_Baccarat_Rouge_540.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440052",
    slug: "maison-francis-kurkdjian-baccarat-rouge-540-extrait",
    title: "Maison Francis Kurkdjian Baccarat Rouge 540 Extrait",
    brand: "Maison Francis Kurkdjian",
    price: [21000, 37800],
    ml: [5, 10],
    season: "fall",
    gender: "unisex",
    description:
      "Baccarat Rouge 540 Extrait — более насыщенная и стойкая версия классического Baccarat Rouge 540, раскрывающая глубокие древесно-амбровые оттенки.",
    img: "/assets/img/perfume/Maison_Francis_Kurkdjian_Baccarat_Rouge_540_EXTRAIT.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440053",
    slug: "maison-francis-kurkdjian-grand-soir",
    title: "Maison Francis Kurkdjian Grand Soir",
    brand: "Maison Francis Kurkdjian",
    price: [19000, 34200],
    ml: [5, 10],
    season: "winter",
    gender: "unisex",
    description:
      "Grand Soir — это тёплый восточный аромат с нотами амбры, бензоина и ванили, создающий элегантное и роскошное вечернее звучание.",
    img: "/assets/img/perfume/Maison_Francis_Kurkdjian_Grand_Soir.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440054",
    slug: "maison-francis-kurkdjian-masculin-pluriel",
    title: "Maison Francis Kurkdjian Masculin Pluriel",
    brand: "Maison Francis Kurkdjian",
    price: [15000, 27000],
    ml: [5, 10],
    season: "spring",
    gender: "male",
    description:
      "Masculin Pluriel — это классический мужской фужерный аромат с нотами лаванды, ветивера и кожи, идеально подходящий для весны.",
    img: "/assets/img/perfume/Maison_Francis_Kurkdjian_Masculin_Pluriel.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440055",
    slug: "maison-francis-kurkdjian-oud-satin-mood",
    title: "Maison Francis Kurkdjian Oud Satin Mood Extrait",
    brand: "Maison Francis Kurkdjian",
    price: [22000, 39600],
    ml: [5, 10],
    season: "winter",
    gender: "unisex",
    description:
      "Oud Satin Mood Extrait — это роскошный, бархатистый удовый аромат с нотами розы, ванили и амбры, создающий тёплое и соблазнительное звучание.",
    img: "/assets/img/perfume/Maison_Francis_Kurkdjian_Oud_Satin_Mood_Extrait_de_parfum.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440056",
    slug: "mancera-cedrat-boise",
    title: "Mancera Cedrat Boise",
    brand: "Mancera",
    price: [12000, 21600],
    ml: [5, 10],
    season: "summer",
    gender: "unisex",
    description:
      "Cedrat Boise — это свежий цитрусово-древесный аромат с нотами лимона, черной смородины и кедра, создающий бодрящее летнее настроение.",
    img: "/assets/img/perfume/Mancera_Cedrat_Boise.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440057",
    slug: "mancera-instant-crush",
    title: "Mancera Instant Crush",
    brand: "Mancera",
    price: [13500, 24300],
    ml: [5, 10],
    season: "fall",
    gender: "unisex",
    description:
      "Instant Crush — это сладкий и пряный аромат с шафраном, жасмином и ванилью, создающий обволакивающее и теплое звучание.",
    img: "/assets/img/perfume/Mancera_Instant_Crush.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440058",
    slug: "mancera-red-tobacco",
    title: "Mancera Red Tobacco",
    brand: "Mancera",
    price: [14000, 25200],
    ml: [5, 10],
    season: "winter",
    gender: "unisex",
    description:
      "Red Tobacco — это насыщенный табачный аромат с нотами уда, специй и ванили, создающий согревающее и харизматичное звучание.",
    img: "/assets/img/perfume/Mancera_Red_Tobacco.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440059",
    slug: "mancera-tonka-cola",
    title: "Mancera Tonka Cola",
    brand: "Mancera",
    price: [13000, 23400],
    ml: [5, 10],
    season: "summer",
    gender: "unisex",
    description:
      "Tonka Cola — это яркий и игривый аромат с нотами вишни, корицы и тонка-бобов, создающий освежающее и сладкое летнее звучание.",
    img: "/assets/img/perfume/Mancera_Tonka_Cola.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440060",
    slug: "marc-antoine-barrois-b683",
    title: "Marc-Antoine Barrois B683",
    brand: "Marc-Antoine Barrois",
    price: [14000, 25200],
    ml: [5, 10],
    season: "fall",
    gender: "male",
    description:
      "B683 — это элегантный древесно-пряный аромат с нотами кожи, специй и сандала, создающий теплое и изысканное осеннее звучание.",
    img: "/assets/img/perfume/Marc_Antoine_Barrois_B683.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440061",
    slug: "marc-antoine-barrois-b683-extrait",
    title: "Marc-Antoine Barrois B683 Extrait",
    brand: "Marc-Antoine Barrois",
    price: [16000, 28800],
    ml: [5, 10],
    season: "winter",
    gender: "male",
    description:
      "B683 Extrait — это более насыщенная версия классического B683 с усиленными кожаными и древесными нотами, идеально подходящая для зимы.",
    img: "/assets/img/perfume/Marc_Antoine_Barrois_B683_Extrait.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440062",
    slug: "marc-antoine-barrois-encelade",
    title: "Marc-Antoine Barrois Encelade",
    brand: "Marc-Antoine Barrois",
    price: [13500, 24300],
    ml: [5, 10],
    season: "spring",
    gender: "unisex",
    description:
      "Encelade — это свежий и динамичный аромат с нотами ревеня, ветивера и кедра, создающий уникальное и энергичное весеннее звучание.",
    img: "/assets/img/perfume/Marc_Antoine_Barrois_Encelade.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440063",
    slug: "marc-antoine-barrois-ganymede",
    title: "Marc-Antoine Barrois Ganymede",
    brand: "Marc-Antoine Barrois",
    price: [15000, 27000],
    ml: [5, 10],
    season: "summer",
    gender: "unisex",
    description:
      "Ganymede — это футуристичный аромат с минеральными и кожаными акцентами, создающий легкое и необычное летнее звучание.",
    img: "/assets/img/perfume/Marc_Antoine_Barrois_Ganymede.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440064",
    slug: "marc-antoine-barrois-ganymede-extrait",
    title: "Marc-Antoine Barrois Ganymede Extrait",
    brand: "Marc-Antoine Barrois",
    price: [17000, 30600],
    ml: [5, 10],
    season: "fall",
    gender: "unisex",
    description:
      "Ganymede Extrait — более интенсивная версия оригинального Ganymede с насыщенными кожаными и древесными нотами, придающими богатую текстуру аромату.",
    img: "/assets/img/perfume/Marc_Antoine_Barrois_Ganymede_Extrait.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440065",
    slug: "matiere-premiere-crystal-saffron",
    title: "Matière Première Crystal Saffron",
    brand: "Matière Première",
    price: [14500, 26100],
    ml: [5, 10],
    season: "spring",
    gender: "unisex",
    description:
      "Crystal Saffron — это яркий и изысканный аромат с доминирующим аккордом шафрана, дополненным древесными и мускусными нотами.",
    img: "/assets/img/perfume/Matiere_Premiere_Crystal_Saffron.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440066",
    slug: "matiere-premiere-falcon-leather",
    title: "Matière Première Falcon Leather",
    brand: "Matière Première",
    price: [15500, 27900],
    ml: [5, 10],
    season: "fall",
    gender: "male",
    description:
      "Falcon Leather — это интенсивный кожаный аромат с нотами шафрана и кедра, создающий богатое и глубокое звучание.",
    img: "/assets/img/perfume/Matiere_Premiere_Falcon_Leather.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440067",
    slug: "matiere-premiere-parisian-musc",
    title: "Matière Première Parisian Musc",
    brand: "Matière Première",
    price: [14000, 25200],
    ml: [5, 10],
    season: "summer",
    gender: "unisex",
    description:
      "Parisian Musc — это нежный и свежий мускусный аромат с цветочными и древесными акцентами, идеально подходящий для жаркого лета.",
    img: "/assets/img/perfume/Matiere_Premiere_Parisian_Musc.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440068",
    slug: "memo-french-leather",
    title: "Memo French Leather",
    brand: "Memo",
    price: [16000, 28800],
    ml: [5, 10],
    season: "fall",
    gender: "unisex",
    description:
      "French Leather — это роскошный аромат с кожаными и розовыми нотами, создающий элегантное и изысканное осеннее звучание.",
    img: "/assets/img/perfume/Memo_French_Leather.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440069",
    slug: "memo-irish-leather",
    title: "Memo Irish Leather",
    brand: "Memo",
    price: [16500, 29700],
    ml: [5, 10],
    season: "winter",
    gender: "unisex",
    description:
      "Irish Leather — это холодный, мощный аромат с нотами кожи, можжевельника и амбры, создающий атмосферу свободы и силы.",
    img: "/assets/img/perfume/Memo_Irish_Leather.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440070",
    slug: "montale-arabians-tonka",
    title: "Montale Arabians Tonka",
    brand: "Montale",
    price: [14000, 25200],
    ml: [5, 10],
    season: "winter",
    gender: "unisex",
    description:
      "Arabians Tonka — это густой, теплый восточный аромат с нотами уда, ванили и бобов тонка, создающий роскошное зимнее звучание.",
    img: "/assets/img/perfume/Montale_Arabians_Tonka.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440071",
    slug: "montale-intense-cafe",
    title: "Montale Intense Cafe",
    brand: "Montale",
    price: [12000, 21600],
    ml: [5, 10],
    season: "fall",
    gender: "unisex",
    description:
      "Intense Cafe — это гурманский аромат с нотами кофе, ванили и розы, создающий уютное и обволакивающее звучание.",
    img: "/assets/img/perfume/Montale_Intense_Cafe.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440072",
    slug: "nasomatto-baraonda",
    title: "Nasomatto Baraonda",
    brand: "Nasomatto",
    price: [16000, 28800],
    ml: [5, 10],
    season: "winter",
    gender: "unisex",
    description:
      "Baraonda — это глубокий и теплый аромат с алкогольными и древесными нотами, создающий согревающее и богатое звучание.",
    img: "/assets/img/perfume/Nasomatto_Baraonda.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440073",
    slug: "nasomatto-black-afgano",
    title: "Nasomatto Black Afgano",
    brand: "Nasomatto",
    price: [18000, 32400],
    ml: [5, 10],
    season: "fall",
    gender: "unisex",
    description:
      "Black Afgano — это мощный, глубокий аромат с нотами уда, смол и табака, создающий загадочное и завораживающее звучание.",
    img: "/assets/img/perfume/Nasomatto_Black_Afgano.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440074",
    slug: "nasomatto-pardon",
    title: "Nasomatto Pardon",
    brand: "Nasomatto",
    price: [15000, 27000],
    ml: [5, 10],
    season: "spring",
    gender: "male",
    description:
      "Pardon — это элегантный и стильный аромат с нотами дерева, ванили и какао, создающий мягкое и утонченное весеннее звучание.",
    img: "/assets/img/perfume/Nasomatto_Pardon.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440075",
    slug: "nishane-ani",
    title: "Nishane Ani",
    brand: "Nishane",
    price: [17000, 30600],
    ml: [5, 10],
    season: "fall",
    gender: "unisex",
    description:
      "Ani — это насыщенный восточный аромат с нотами ванили, имбиря и цитрусов, создающий теплое и уютное звучание.",
    img: "/assets/img/perfume/Nishane_Ani.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440076",
    slug: "nishane-fan-your-flames",
    title: "Nishane Fan Your Flames",
    brand: "Nishane",
    price: [16000, 28800],
    ml: [5, 10],
    season: "winter",
    gender: "unisex",
    description:
      "Fan Your Flames — это глубокий и теплый аромат с нотами кокоса, рома и табака, создающий атмосферу уюта и релакса.",
    img: "/assets/img/perfume/Nishane_Fan_Your_Flames.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440077",
    slug: "nishane-kredo",
    title: "Nishane Kredo",
    brand: "Nishane",
    price: [18500, 33300],
    ml: [5, 10],
    season: "fall",
    gender: "unisex",
    description:
      "Kredo — это насыщенный, теплый аромат с нотами уда, специй и кожи, создающий мощное и элегантное звучание.",
    img: "/assets/img/perfume/Nishane_Kredo.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440078",
    slug: "nishane-nefs-extrait",
    title: "Nishane Nefs Extrait",
    brand: "Nishane",
    price: [25000, 45000],
    ml: [5, 10],
    season: "winter",
    gender: "unisex",
    description:
      "Nefs Extrait — это роскошный восточный аромат с нотами меда, уда и шафрана, создающий дорогое и гипнотическое звучание.",
    img: "/assets/img/perfume/Nishane_Nefs_Extrait.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440079",
    slug: "orto-parisi-cuoium",
    title: "Orto Parisi Cuoium",
    brand: "Orto Parisi",
    price: [20000, 36000],
    ml: [5, 10],
    season: "fall",
    gender: "unisex",
    description:
      "Cuoium — это насыщенный кожаный аромат с нотами меда, табака и смол, создающий мощное и запоминающееся звучание.",
    img: "/assets/img/perfume/Orto_Parisi_Cuoium.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440080",
    slug: "orto-parisi-megamare",
    title: "Orto Parisi Megamare",
    brand: "Orto Parisi",
    price: [19000, 34200],
    ml: [5, 10],
    season: "summer",
    gender: "unisex",
    description:
      "Megamare — это свежий морской аромат с мощными акватическими и солеными нотами, создающий ощущение бескрайнего океана.",
    img: "/assets/img/perfume/Orto_Parisi_Megamare.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440081",
    slug: "orto-parisi-terroni",
    title: "Orto Parisi Terroni",
    brand: "Orto Parisi",
    price: [17500, 31500],
    ml: [5, 10],
    season: "fall",
    gender: "unisex",
    description:
      "Terroni — это интенсивный дымный аромат с древесными и земными нотами, создающий мощное и богатое звучание.",
    img: "/assets/img/perfume/Orto_Parisi_Terroni.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440082",
    slug: "parfums-de-marly-carlisle",
    title: "Parfums de Marly Carlisle",
    brand: "Parfums de Marly",
    price: [20000, 36000],
    ml: [5, 10],
    season: "fall",
    gender: "male",
    description:
      "Carlisle — это роскошный восточный аромат с нотами яблока, ванили и пачули, создающий теплое и элегантное звучание.",
    img: "/assets/img/perfume/Parfums_de_Marly_Carlisle.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440083",
    slug: "parfums-de-marly-godolphin",
    title: "Parfums de Marly Godolphin",
    brand: "Parfums de Marly",
    price: [18000, 32400],
    ml: [5, 10],
    season: "spring",
    gender: "male",
    description:
      "Godolphin — это роскошный кожаный аромат с фруктовыми и табачными нотами, создающий элегантное и благородное звучание.",
    img: "/assets/img/perfume/Parfums_de_Marly_Godolphin.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440084",
    slug: "parfums-de-marly-haltane",
    title: "Parfums de Marly Haltane",
    brand: "Parfums de Marly",
    price: [21000, 37800],
    ml: [5, 10],
    season: "fall",
    gender: "male",
    description:
      "Haltane — это элегантный древесно-амбровый аромат с зелеными и пряными акцентами, создающий благородное и теплое звучание.",
    img: "/assets/img/perfume/Parfums_de_Marly_Haltane.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440085",
    slug: "parfums-de-marly-layton",
    title: "Parfums de Marly Layton",
    brand: "Parfums de Marly",
    price: [19000, 34200],
    ml: [5, 10],
    season: "fall",
    gender: "male",
    description:
      "Layton — это утонченный восточно-пряный аромат с нотами яблока, ванили и кардамона, создающий теплое и элегантное звучание.",
    img: "/assets/img/perfume/Parfums_De_Marly_Layton.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440086",
    slug: "parfums-de-marly-pegasus-exclusif",
    title: "Parfums de Marly Pegasus Exclusif",
    brand: "Parfums de Marly",
    price: [22000, 39600],
    ml: [5, 10],
    season: "winter",
    gender: "male",
    description:
      "Pegasus Exclusif — это насыщенный восточный аромат с миндальными и амбровыми нотами, создающий глубокое и выразительное звучание.",
    img: "/assets/img/perfume/Parfums_de_Marly_Pegasus_Exclusif.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440087",
    slug: "parfums-de-marly-perseus",
    title: "Parfums de Marly Perseus",
    brand: "Parfums de Marly",
    price: [19500, 35100],
    ml: [5, 10],
    season: "summer",
    gender: "male",
    description:
      "Perseus — это бодрящий цитрусовый аромат с нотами грейпфрута, ветивера и мускуса, создающий легкое и освежающее летнее звучание.",
    img: "/assets/img/perfume/Parfums_de_Marly_Perseus.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440088",
    slug: "penhaligons-halfeti",
    title: "Penhaligon's Halfeti",
    brand: "Penhaligon's",
    price: [16000, 28800],
    ml: [5, 10],
    season: "fall",
    gender: "unisex",
    description:
      "Halfeti — это теплый восточный аромат с нотами уда, шафрана и специй, создающий загадочное и богатое звучание.",
    img: "/assets/img/perfume/Penhaligon_s_Halfeti.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440089",
    slug: "penhaligons-legacy-of-petra",
    title: "Penhaligon's Legacy of Petra",
    brand: "Penhaligon's",
    price: [17000, 30600],
    ml: [5, 10],
    season: "fall",
    gender: "unisex",
    description:
      "Legacy of Petra — это пряный восточный аромат с нотами ладана, ванили и шафрана, создающий богатое и теплое звучание.",
    img: "/assets/img/perfume/Penhaligon_s_Legacy_of_Petra.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440090",
    slug: "penhaligons-the-blazing-mister-sam",
    title: "Penhaligon's The Blazing Mister Sam",
    brand: "Penhaligon's",
    price: [18500, 33300],
    ml: [5, 10],
    season: "winter",
    gender: "male",
    description:
      "The Blazing Mister Sam — это насыщенный пряный аромат с нотами кардамона, тмина и табака, создающий мощное и харизматичное звучание.",
    img: "/assets/img/perfume/Penhaligon_s_The_Blazing_Mister_Sam.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440091",
    slug: "penhaligons-the-omniscient-mr-thompson",
    title: "Penhaligon's The Omniscient Mr Thompson",
    brand: "Penhaligon's",
    price: [17500, 31500],
    ml: [5, 10],
    season: "fall",
    gender: "male",
    description:
      "The Omniscient Mr Thompson — это утонченный древесно-пряный аромат с нотами кедра, кожи и ладана, создающий элегантное и уверенное звучание.",
    img: "/assets/img/perfume/Penhaligon_s_The_Omniscient_Mr_Thompson.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440092",
    slug: "penhaligons-vra-vra-vroom",
    title: "Penhaligon's Vra Vra Vroom",
    brand: "Penhaligon's",
    price: [16000, 28800],
    ml: [5, 10],
    season: "spring",
    gender: "unisex",
    description:
      "Vra Vra Vroom — это энергичный и бодрящий аромат с цитрусовыми и древесными нотами, идеально подходящий для весеннего сезона.",
    img: "/assets/img/perfume/Penhaligon_s_Vra_Vra_Vroom.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440093",
    slug: "roja-amber-aoud-crystal",
    title: "Roja Amber Aoud Crystal",
    brand: "Roja Parfums",
    price: [25000, 45000],
    ml: [5, 10],
    season: "winter",
    gender: "unisex",
    description:
      "Amber Aoud Crystal — это роскошный восточный аромат с нотами уда, амбры и шафрана, создающий глубокое и завораживающее звучание.",
    img: "/assets/img/perfume/Roja_Amber_Aoud_Crystal.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440094",
    slug: "roja-aoud-extraordinaire",
    title: "Roja Aoud Extraordinaire",
    brand: "Roja Parfums",
    price: [27000, 48600],
    ml: [5, 10],
    season: "fall",
    gender: "unisex",
    description:
      "Aoud Extraordinaire — это насыщенный удовый аромат с глубокими древесными и специевыми нотами, создающий элегантное и стойкое звучание.",
    img: "/assets/img/perfume/Roja_Aoud_Extraordinaire.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440095",
    slug: "roja-apex",
    title: "Roja Apex",
    brand: "Roja Parfums",
    price: [23000, 41400],
    ml: [5, 10],
    season: "summer",
    gender: "unisex",
    description:
      "Apex — это бодрящий цитрусово-древесный аромат с нотами ананаса, ладана и ветивера, создающий легкое и освежающее летнее звучание.",
    img: "/assets/img/perfume/Roja_Apex.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440096",
    slug: "roja-burlington-1819",
    title: "Roja Burlington 1819",
    brand: "Roja Parfums",
    price: [21000, 37800],
    ml: [5, 10],
    season: "spring",
    gender: "unisex",
    description:
      "Burlington 1819 — это утонченный фужерный аромат с цитрусовыми, древесными и пряными акцентами, создающий классическое и благородное звучание.",
    img: "/assets/img/perfume/Roja_Burlington_1819.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440097",
    slug: "roja-elysium-cologne",
    title: "Roja Elysium Cologne",
    brand: "Roja Parfums",
    price: [20000, 36000],
    ml: [5, 10],
    season: "summer",
    gender: "male",
    description:
      "Elysium Cologne — это свежий и легкий цитрусовый аромат с нотами грейпфрута, можжевельника и мускуса, создающий бодрящее летнее звучание.",
    img: "/assets/img/perfume/Roja_Elysuim_Cologne.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440098",
    slug: "roja-musk-aoud",
    title: "Roja Musk Aoud",
    brand: "Roja Parfums",
    price: [28000, 50400],
    ml: [5, 10],
    season: "winter",
    gender: "unisex",
    description:
      "Musk Aoud — это богатый и сложный аромат с удами, мускусными и специевыми нотами, создающий тёплое и роскошное звучание.",
    img: "/assets/img/perfume/Roja_Musk_Aoud.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440099",
    slug: "roja-oceania",
    title: "Roja Oceania",
    brand: "Roja Parfums",
    price: [19000, 34200],
    ml: [5, 10],
    season: "summer",
    gender: "unisex",
    description:
      "Oceania — это освежающий морской аромат с цитрусовыми и зелеными нотами, создающий ощущение бескрайнего океана и морского бриза.",
    img: "/assets/img/perfume/Roja_Oceania.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440100",
    slug: "serge-lutens-ambre-sultan",
    title: "Serge Lutens Ambre Sultan",
    brand: "Serge Lutens",
    price: [17000, 30600],
    ml: [5, 10],
    season: "fall",
    gender: "female",
    description:
      "Ambre Sultan — это глубокий и теплый амбровый аромат с нотами ванили, бензоина и специй, создающий роскошное осеннее звучание.",
    img: "/assets/img/perfume/Serge_Lutens_Ambre_Sultan.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440101",
    slug: "serge-lutens-fleurs-d-oranger",
    title: "Serge Lutens Fleurs d’Oranger",
    brand: "Serge Lutens",
    price: [15000, 27000],
    ml: [5, 10],
    season: "spring",
    gender: "female",
    description:
      "Fleurs d’Oranger — это цветочный аромат с доминирующими нотами апельсинового цвета, туберозы и жасмина, создающий нежное весеннее настроение.",
    img: "/assets/img/perfume/Serge_Lutens_Fleurs_d_Oranger.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440102",
    slug: "sospiro-basso",
    title: "Sospiro Basso",
    brand: "Sospiro",
    price: [18500, 33300],
    ml: [5, 10],
    season: "summer",
    gender: "female",
    description:
      "Basso — это яркий и жизнерадостный аромат с цитрусовыми и фруктовыми нотами, создающий легкое и освежающее летнее звучание.",
    img: "/assets/img/perfume/Sospiro_Basso.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440103",
    slug: "stefano-ricci-firenze",
    title: "Stefano Ricci Firenze",
    brand: "Stefano Ricci",
    price: [22000, 39600],
    ml: [5, 10],
    season: "fall",
    gender: "female",
    description:
      "Firenze — это элегантный восточный аромат с нотами шафрана, жасмина и амбры, создающий утонченное осеннее звучание.",
    img: "/assets/img/perfume/Stefano_Ricci_Firenze.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440104",
    slug: "stefano-ricci-royal-eagle-gold",
    title: "Stefano Ricci Royal Eagle Gold",
    brand: "Stefano Ricci",
    price: [24000, 43200],
    ml: [5, 10],
    season: "winter",
    gender: "female",
    description:
      "Royal Eagle Gold — это роскошный и насыщенный аромат с нотами белых цветов, ванили и мускуса, создающий тёплое и чувственное звучание.",
    img: "/assets/img/perfume/Stefano_Ricci_Royal_Eagle_Gold.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440105",
    slug: "stephane-humbert-lucas-777-black-gemstone",
    title: "Stephane Humbert Lucas 777 Black Gemstone",
    brand: "Stephane Humbert Lucas 777",
    price: [19500, 35100],
    ml: [5, 10],
    season: "fall",
    gender: "female",
    description:
      "Black Gemstone — это таинственный восточный аромат с нотами уда, шафрана и розы, создающий загадочное и магнетическое звучание.",
    img: "/assets/img/perfume/Stephane_Humbert_Lucas_777_Black_Gemstone.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440106",
    slug: "stephane-humbert-lucas-777-soleil-de-jeddah",
    title: "Stephane Humbert Lucas 777 Soleil de Jeddah",
    brand: "Stephane Humbert Lucas 777",
    price: [21000, 37800],
    ml: [5, 10],
    season: "summer",
    gender: "female",
    description:
      "Soleil de Jeddah — это солнечный и сияющий аромат с нотами цитрусов, белых цветов и амбры, создающий тёплое летнее настроение.",
    img: "/assets/img/perfume/Stephane_Humbert_Lucas_777_Soleil_de_Jeddah.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440107",
    slug: "thomas-kosmala-n4-neon",
    title: "Thomas Kosmala No.4 Neon",
    brand: "Thomas Kosmala",
    price: [13000, 23400],
    ml: [5, 10],
    season: "spring",
    gender: "female",
    description:
      "No.4 Neon — это игривый и бодрящий аромат с цитрусовыми и цветочными нотами, создающий жизнерадостное и энергичное весеннее звучание.",
    img: "/assets/img/perfume/Thomas_Kosmala_N4_NEON.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440108",
    slug: "thomas-kosmala-n4-sport",
    title: "Thomas Kosmala No.4 Sport",
    brand: "Thomas Kosmala",
    price: [12500, 22500],
    ml: [5, 10],
    season: "summer",
    gender: "female",
    description:
      "No.4 Sport — это свежий и бодрящий аромат с нотами цитрусов, зелени и белого мускуса, создающий легкость и энергию летнего дня.",
    img: "/assets/img/perfume/Thomas_Kosmala_N4_Sport.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440109",
    slug: "thomas-kosmala-no4-apres-l-amour",
    title: "Thomas Kosmala No.4 Après l’Amour",
    brand: "Thomas Kosmala",
    price: [14000, 25200],
    ml: [5, 10],
    season: "fall",
    gender: "female",
    description:
      "Après l’Amour — это чувственный древесно-мускусный аромат с нотами амбры, цитрусов и лаванды, создающий элегантное осеннее звучание.",
    img: "/assets/img/perfume/Thomas_Kosmala_No__4_Apres_l_Amour.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440118",
    slug: "areej-le-dore-russian-oud",
    title: "Areej Le Doré Russian Oud",
    brand: "Areej Le Doré",
    price: [25000, 45000],
    ml: [5, 10],
    season: "winter",
    gender: "male",
    description:
      "Russian Oud — это мощный и дымный удовый аромат с нотами кожи, амбры и специй, создающий выразительное зимнее звучание.",
    img: "/assets/img/perfume/Areej_le_Dore___Russian_Oud.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440119",
    slug: "areej-le-dore-ottoman-empire-iv",
    title: "Areej Le Doré Ottoman Empire IV",
    brand: "Areej Le Doré",
    price: [27000, 48600],
    ml: [5, 10],
    season: "fall",
    gender: "unisex",
    description:
      "Ottoman Empire IV — это насыщенный восточный аромат с нотами розы, уда и мускуса, создающий таинственное и богатое звучание.",
    img: "/assets/img/perfume/Areej_le_Dore_Ottoman_Empire_IV.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440120",
    slug: "bortnikoff-chypre-du-nord",
    title: "Bortnikoff Chypre du Nord",
    brand: "Bortnikoff",
    price: [19000, 34200],
    ml: [5, 10],
    season: "spring",
    gender: "unisex",
    description:
      "Chypre du Nord — это элегантный шипровый аромат с нотами цитрусов, дубового мха и пачули, создающий классическое весеннее звучание.",
    img: "/assets/img/perfume/Bortnikoff_Chypre_du_Nord.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440121",
    slug: "bortnikoff-dream",
    title: "Bortnikoff Dream",
    brand: "Bortnikoff",
    price: [20000, 36000],
    ml: [5, 10],
    season: "summer",
    gender: "female",
    description:
      "Dream — это нежный и романтичный аромат с нотами белых цветов, ванили и мускуса, создающий легкое и мечтательное летнее настроение.",
    img: "/assets/img/perfume/Bortnikoff_Dream.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440122",
    slug: "bortnikoff-marakesh",
    title: "Bortnikoff Marakesh",
    brand: "Bortnikoff",
    price: [22000, 39600],
    ml: [5, 10],
    season: "fall",
    gender: "unisex",
    description:
      "Marakesh — это пряный восточный аромат с нотами шафрана, кожи и уда, создающий теплое и загадочное осеннее звучание.",
    img: "/assets/img/perfume/Bortnikoff_Marakesh.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440123",
    slug: "bortnikoff-musk-cologne",
    title: "Bortnikoff Musk Cologne",
    brand: "Bortnikoff",
    price: [18000, 32400],
    ml: [5, 10],
    season: "spring",
    gender: "male",
    description:
      "Musk Cologne — это свежий мускусный аромат с цитрусовыми и древесными нотами, создающий бодрящее весеннее звучание.",
    img: "/assets/img/perfume/Bortnikoff_Musk_Cologne.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440124",
    slug: "bortnikoff-musk-habib",
    title: "Bortnikoff Musk Habib",
    brand: "Bortnikoff",
    price: [23000, 41400],
    ml: [5, 10],
    season: "winter",
    gender: "female",
    description:
      "Musk Habib — это тёплый и чувственный мускусный аромат с нотами ванили, розы и амбры, создающий роскошное зимнее звучание.",
    img: "/assets/img/perfume/Bortnikoff_Musk_Habib.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440125",
    slug: "bortnikoff-oud-maximus",
    title: "Bortnikoff Oud Maximus",
    brand: "Bortnikoff",
    price: [25000, 45000],
    ml: [5, 10],
    season: "fall",
    gender: "male",
    description:
      "Oud Maximus — это насыщенный удовый аромат с кожаными и смолистыми нотами, создающий богатое и выразительное звучание.",
    img: "/assets/img/perfume/Bortnikoff_Oud_Maximus.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440126",
    slug: "bortnikoff-oud-monarch",
    title: "Bortnikoff Oud Monarch",
    brand: "Bortnikoff",
    price: [27000, 48600],
    ml: [5, 10],
    season: "winter",
    gender: "unisex",
    description:
      "Oud Monarch — это утонченный и насыщенный удовый аромат с нотами табака, ванили и меда, создающий богатое зимнее звучание.",
    img: "/assets/img/perfume/Bortnikoff_Oud_Monarch.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440127",
    slug: "bortnikoff-sayat-nova",
    title: "Bortnikoff Sayat Nova",
    brand: "Bortnikoff",
    price: [19500, 35100],
    ml: [5, 10],
    season: "spring",
    gender: "female",
    description:
      "Sayat Nova — это мягкий и романтичный аромат с нотами ванили, цветочного нектара и бобов тонка, создающий легкое и элегантное весеннее звучание.",
    img: "/assets/img/perfume/Bortnikoff_Sayat_Nova.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440128",
    slug: "bortnikoff-tabac-dore",
    title: "Bortnikoff Tabac Doré",
    brand: "Bortnikoff",
    price: [20000, 36000],
    ml: [5, 10],
    season: "fall",
    gender: "male",
    description:
      "Tabac Doré — это насыщенный табачный аромат с нотами ванили, меда и древесных акцентов, создающий тёплое осеннее звучание.",
    img: "/assets/img/perfume/Bortnikoff_Tabac_Dore.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440129",
    slug: "bvlgari-kobraa",
    title: "BVLGARI Kobraa",
    brand: "BVLGARI",
    price: [18000, 32400],
    ml: [5, 10],
    season: "fall",
    gender: "male",
    description:
      "Kobraa — это загадочный и мощный аромат с нотами ладана, герани и кожи, создающий элегантное осеннее звучание.",
    img: "/assets/img/perfume/BVLGARI_Kobraa.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440130",
    slug: "bvlgari-orom",
    title: "BVLGARI Orom",
    brand: "BVLGARI",
    price: [19500, 35100],
    ml: [5, 10],
    season: "summer",
    gender: "male",
    description:
      "Orom — это бодрящий цитрусово-древесный аромат с нотами грейпфрута, ветивера и специй, создающий освежающее летнее звучание.",
    img: "/assets/img/perfume/BVLGARI_Orom.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440132",
    slug: "clive-christian-x-masculine",
    title: "Clive Christian X Masculine",
    brand: "Clive Christian",
    price: [23000, 41400],
    ml: [5, 10],
    season: "winter",
    gender: "male",
    description:
      "X Masculine — это мощный древесно-пряный аромат с нотами кардамона, имбиря и амбры, создающий уверенное зимнее звучание.",
    img: "/assets/img/perfume/Clive_Christian_X_Masculine.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440133",
    slug: "creed-centaurus",
    title: "Creed Centaurus",
    brand: "Creed",
    price: [18500, 33300],
    ml: [5, 10],
    season: "fall",
    gender: "male",
    description:
      "Centaurus — это элегантный древесно-фужерный аромат с нотами бергамота, лаванды и дубового мха, создающий классическое осеннее звучание.",
    img: "/assets/img/perfume/Creed_Centaurus.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440134",
    slug: "creed-pure-white-cologne",
    title: "Creed Pure White Cologne",
    brand: "Creed",
    price: [21000, 37800],
    ml: [5, 10],
    season: "summer",
    gender: "male",
    description:
      "Pure White Cologne — это легкий цитрусово-мускусный аромат с нотами лимона, розы и нероли, создающий бодрящее летнее звучание.",
    img: "/assets/img/perfume/Creed_Pure_White_Cologne_Les_Royales_Exclusives.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440135",
    slug: "dior-ambre-nuit",
    title: "Dior Ambre Nuit",
    brand: "Dior",
    price: [17000, 30600],
    ml: [5, 10],
    season: "fall",
    gender: "female",
    description:
      "Ambre Nuit — это утонченный амбровый аромат с нотами розы, специй и цитрусов, создающий элегантное осеннее звучание.",
    img: "/assets/img/perfume/Dior_Ambre_Nuit.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440136",
    slug: "ex-nihilo-outcast-blue",
    title: "Ex Nihilo Outcast Blue Extrait",
    brand: "Ex Nihilo",
    price: [23000, 41400],
    ml: [5, 10],
    season: "winter",
    gender: "male",
    description:
      "Outcast Blue Extrait — это насыщенный кожаный аромат с нотами уда, лаванды и пряностей, создающий стойкое зимнее звучание.",
    img: "/assets/img/perfume/Ex_Nihilo_Outcast_Blue_Extrait_de_Parfum.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440137",
    slug: "fort-and-manle-v-for-vetiver",
    title: "Fort & Manle V for Vetiver",
    brand: "Fort & Manle",
    price: [19000, 34200],
    ml: [5, 10],
    season: "summer",
    gender: "male",
    description:
      "V for Vetiver — это бодрящий и элегантный аромат с нотами цитрусов, ветивера и лаванды, создающий легкость и свежесть летнего дня.",
    img: "/assets/img/perfume/Fort_and_Manle_V_for_vetiver.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440138",
    slug: "gucci-the-voice-of-the-snake",
    title: "Gucci The Voice of the Snake",
    brand: "Gucci",
    price: [19500, 35100],
    ml: [5, 10],
    season: "fall",
    gender: "male",
    description:
      "The Voice of the Snake — это таинственный древесно-удовый аромат с нотами кожи, уда и специй, создающий загадочное осеннее звучание.",
    img: "/assets/img/perfume/Gucci_The_Voice_Of_The_Snake.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440139",
    slug: "initio-oud-for-greatness",
    title: "INITIO Oud for Greatness",
    brand: "INITIO",
    price: [23000, 41400],
    ml: [5, 10],
    season: "winter",
    gender: "unisex",
    description:
      "Oud for Greatness — это благородный удовый аромат с лавандой, шафраном и мускусом, создающий роскошное зимнее звучание.",
    img: "/assets/img/perfume/INITIO_Oud_For_Greatness.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440140",
    slug: "initio-paragon",
    title: "INITIO Paragon",
    brand: "INITIO",
    price: [18000, 32400],
    ml: [5, 10],
    season: "spring",
    gender: "male",
    description:
      "Paragon — это мистический древесно-пряный аромат с нотами шалфея, лаванды и сандала, создающий утонченное весеннее звучание.",
    img: "/assets/img/perfume/INITIO_Paragon.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440141",
    slug: "kilian-straight-to-heaven",
    title: "Kilian Straight to Heaven White Cristal",
    brand: "Kilian",
    price: [21000, 37800],
    ml: [5, 10],
    season: "fall",
    gender: "male",
    description:
      "Straight to Heaven — это богатый древесно-амбровый аромат с нотами рома, пачули и кедра, создающий харизматичное осеннее звучание.",
    img: "/assets/img/perfume/Kilian_Straight_to_Heaven_White_Cristal.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440142",
    slug: "kilian-vodka-on-the-rocks",
    title: "Kilian Vodka on the Rocks",
    brand: "Kilian",
    price: [18500, 33300],
    ml: [5, 10],
    season: "summer",
    gender: "male",
    description:
      "Vodka on the Rocks — это свежий и бодрящий аромат с нотами кориандра, кардамона и цитрусов, создающий прохладное летнее звучание.",
    img: "/assets/img/perfume/Kilian_Vodka_on_the_Rocks.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440143",
    slug: "louis-vuitton-nuit-de-feu",
    title: "Louis Vuitton Nuit de Feu",
    brand: "Louis Vuitton",
    price: [25000, 45000],
    ml: [5, 10],
    season: "winter",
    gender: "male",
    description:
      "Nuit de Feu — это глубокий дымный аромат с нотами ладана, амбры и уда, создающий мистическое зимнее звучание.",
    img: "/assets/img/perfume/Louis_Vuitton_Nuit_de_Feu.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440144",
    slug: "maison-francis-kurkdjian-baccarat-rouge-540",
    title: "Maison Francis Kurkdjian Baccarat Rouge 540",
    brand: "Maison Francis Kurkdjian",
    price: [20000, 36000],
    ml: [5, 10],
    season: "fall",
    gender: "female",
    description:
      "Baccarat Rouge 540 — это культовый сладкий аромат с нотами шафрана, жасмина и амбры, создающий сияющее осеннее звучание.",
    img: "/assets/img/perfume/Maison_Francis_Kurkdjian_Baccarat_Rouge_540.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440145",
    slug: "mancera-instant-crush",
    title: "Mancera Instant Crush",
    brand: "Mancera",
    price: [17000, 30600],
    ml: [5, 10],
    season: "spring",
    gender: "female",
    description:
      "Instant Crush — это сладкий восточный аромат с нотами шафрана, ванили и цитрусов, создающий романтичное весеннее звучание.",
    img: "/assets/img/perfume/Mancera_Instant_Crush.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440146",
    slug: "nishane-ani",
    title: "Nishane Ani",
    brand: "Nishane",
    price: [19500, 35100],
    ml: [5, 10],
    season: "fall",
    gender: "female",
    description:
      "Ani — это яркий и насыщенный ванильный аромат с имбирем, кардамоном и цитрусами, создающий уютное осеннее звучание.",
    img: "/assets/img/perfume/Nishane_Ani.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440147",
    slug: "roja-musk-aoud",
    title: "Roja Musk Aoud",
    brand: "Roja Parfums",
    price: [26000, 46800],
    ml: [5, 10],
    season: "winter",
    gender: "male",
    description:
      "Musk Aoud — это насыщенный восточный аромат с удами, мускусом и шафраном, создающий богатое и стойкое зимнее звучание.",
    img: "/assets/img/perfume/Roja_Musk_Aoud.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440148",
    slug: "roja-oceania",
    title: "Roja Oceania",
    brand: "Roja Parfums",
    price: [20000, 36000],
    ml: [5, 10],
    season: "summer",
    gender: "unisex",
    description:
      "Oceania — это бодрящий морской аромат с цитрусовыми и зелеными нотами, создающий ощущение свежести и свободы летнего дня.",
    img: "/assets/img/perfume/Roja_Oceania.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440150",
    slug: "dior-oud-ispahan",
    title: "Dior Oud Ispahan",
    brand: "Dior",
    price: [25000, 45000],
    ml: [5, 10],
    season: "winter",
    gender: "unisex",
    description:
      "Oud Ispahan — это восточный аромат с нотами уда, розы и смол, создающий богатое и теплое зимнее звучание.",
    img: "/assets/img/perfume/Dior_Oud_Ispahan.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440151",
    slug: "fort-and-manle-fatih-sultan-mehmed",
    title: "Fort & Manle Fatih Sultan Mehmed",
    brand: "Fort & Manle",
    price: [22000, 39600],
    ml: [5, 10],
    season: "fall",
    gender: "male",
    description:
      "Fatih Sultan Mehmed — это исторически вдохновленный аромат с нотами розы, амбры и уда, создающий величественное осеннее звучание.",
    img: "/assets/img/perfume/Fort_and_Manle_Fatih_Sultan_Mehmed.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440152",
    slug: "penhaligons-the-blazing-mister-sam",
    title: "Penhaligon's The Blazing Mister Sam",
    brand: "Penhaligon's",
    price: [19000, 34200],
    ml: [5, 10],
    season: "winter",
    gender: "male",
    description:
      "The Blazing Mister Sam — это пряный и дерзкий аромат с нотами кардамона, черного перца и пачули, создающий мощное зимнее звучание.",
    img: "/assets/img/perfume/Penhaligon_s_The_Blazing_Mister_Sam.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440153",
    slug: "montale-intense-cafe",
    title: "Montale Intense Cafe",
    brand: "Montale",
    price: [16000, 28800],
    ml: [5, 10],
    season: "fall",
    gender: "female",
    description:
      "Intense Cafe — это гурманский аромат с насыщенными кофейными, ванильными и цветочными нотами, создающий уютное осеннее звучание.",
    img: "/assets/img/perfume/Montale_Intense_Cafe.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440154",
    slug: "nasomatto-baraonda",
    title: "Nasomatto Baraonda",
    brand: "Nasomatto",
    price: [20000, 36000],
    ml: [5, 10],
    season: "winter",
    gender: "unisex",
    description:
      "Baraonda — это древесно-алкогольный аромат с нотами виски, меда и амбры, создающий согревающее зимнее звучание.",
    img: "/assets/img/perfume/Nasomatto_Baraonda.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440155",
    slug: "mancera-red-tobacco",
    title: "Mancera Red Tobacco",
    brand: "Mancera",
    price: [17000, 30600],
    ml: [5, 10],
    season: "fall",
    gender: "male",
    description:
      "Red Tobacco — это мощный табачный аромат с нотами уда, ванили и специй, создающий выразительное осеннее звучание.",
    img: "/assets/img/perfume/Mancera_Red_Tobacco.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440156",
    slug: "memo-french-leather",
    title: "Memo French Leather",
    brand: "Memo",
    price: [19500, 35100],
    ml: [5, 10],
    season: "fall",
    gender: "female",
    description:
      "French Leather — это утонченный аромат с нотами розы, лайма и кожи, создающий элегантное осеннее звучание.",
    img: "/assets/img/perfume/Memo_French_Leather.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440157",
    slug: "serge-lutens-ambre-sultan",
    title: "Serge Lutens Ambre Sultan",
    brand: "Serge Lutens",
    price: [17000, 30600],
    ml: [5, 10],
    season: "winter",
    gender: "male",
    description:
      "Ambre Sultan — это теплый амбровый аромат с нотами ванили, смол и специй, создающий насыщенное зимнее звучание.",
    img: "/assets/img/perfume/Serge_Lutens_Ambre_Sultan.jpg",
  },
];

export const brands = [...new Set(perfumes.map((perfume) => perfume.brand))];
