import { ParfumeEntity } from "@/entities/parfume/model/parfume";

export const perfumes: ParfumeEntity[] = [
  {
    id: "550e8400-e29b-41d4-a716-446655440000",
    slug: "interlude-for-men",
    title: "Interlude For Men",
    brand: "Amouage",
    price: [11000, 20000],
    ml: [5, 10],
    season: "winter",
    gender: "male",
    description:
      "Interlude - это пряно-древесный аромат, который открывается пикантным бергамотом, орегано и маслом ягод пименто, создавая ощущение хаоса и напряжения. В сердце появляются амбра, ладан и опопонакс, которые добавляют глубину и теплоту. База состоит из насыщенных нот уда, сандалового дерева, кожи и пачули, завершая композицию сложностью и утонченностью.",
    img: "/assets/img/perfume/Amouage_Interlude_For_Men.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440001",
    slug: "blue-sapphire",
    title: "Blue Sapphire",
    brand: "Boadicea the Victorious",
    price: [23000, 42000],
    ml: [5, 10],
    season: "fall",
    gender: "unisex",
    description:
      "Царственное слияние цитрусовых нот и зеленых аккордов с гармоничными оттенками розы, кардамона, индийского жасмина, уда и пачули. Blue Sapphire - это благородный аромат, вдохновленный сиянием драгоценного камня, воплощающий роскошь и элегантность.",
    img: "/assets/img/perfume/boadicea_blue_sapphire.webp",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440002",
    slug: "reflection-45",
    title: "Reflection 45",
    brand: "Amouage",
    price: [15000, 27000],
    ml: [5, 10],
    season: "spring",
    gender: "male",
    description:
      "Reflection 45 Man стал более насыщенным, мощным и продуманным. Благодаря щедрой 45-процентной концентрации композиция раскрывает сложные и многослойные ноты, переплетающиеся с древесными и пряными оттенками. Это современная интерпретация классического Reflection Man с усиленной глубиной и стойкостью.",
    img: "/assets/img/perfume/Amouage_Reflection_45.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440003",
    slug: "black-hashish",
    title: "Black Hashish",
    brand: "Arte Olfatto",
    price: [4400, 7920],
    ml: [5, 10],
    season: "winter",
    gender: "male",
    description:
      "Black Hashish - теплый и обволакивающий аромат с запахом ладана и крепкого дыма. Он обладает насыщенным и гипнотическим настроением, в котором сочетаются аккорды черного дерева, смолистых нот и пряных специй, создавая атмосферу загадочности и утонченности.",
    img: "/assets/img/perfume/arte_olfatto_black_hashish.webp",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440004",
    slug: "gris-charnel-extrait",
    title: "Gris Charnel Extrait",
    brand: "BDK Parfums",
    price: [9350, 16830],
    ml: [5, 10],
    season: "fall",
    gender: "unisex",
    description:
      "Gris Charnel Extrait раскрывает интенсивность оригинальной подписи, чтобы извлечь более богатую и многогранную версию. Пряная теплая основа из кардамона и черного чая смешивается с элегантной инжирной сладостью, а затем дополняется мощными древесными аккордами и сладкой ванилью.",
    img: "/assets/img/perfume/bdk_gris_charnel.webp",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440005",
    slug: "orom",
    title: "Orom",
    brand: "BVLGARI",
    price: [18000, 31000],
    ml: [5, 10],
    season: "summer",
    gender: "male",
    description:
      "Погрузитесь в калейдоскоп зелени и синевы живописного острова Мадагаскар — земли, хранящей геологические сокровища, такие как магический лабрадорит. Этот удивительный камень, рожденный природой, завораживает своими волшебными переливами, похожими на танец полярного сияния, околдовывая игрой света и цвета",
    img: "/assets/img/perfume/bdk_oud_abramad.png",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440006",
    slug: "bodacious",
    title: "Bodacious",
    brand: "Boadicea the Victorious",
    price: [13000, 23000],
    ml: [5, 10],
    season: "spring",
    gender: "female",
    description:
      "Bodacious - это атака на чувства, соблазняющая, ошеломляющая и превосходная на каждом шагу. Композиция наполнена роскошными фруктовыми и цветочными нотами, приправленными тёплыми специями, создавая дерзкий и страстный аромат.",
    img: "/assets/img/perfume/boadicea_bodacious.webp",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440007",
    slug: "dragon",
    title: "Dragon",
    brand: "Boadicea the Victorious",
    price: [44000, 79200],
    ml: [5, 10],
    season: "winter",
    gender: "unisex",
    description:
      "С первых мгновений этого утонченного аромата ощущается мощь и изящество дракона. Великолепное сочетание цветочных, древесных и восточных нот, придающих аромату энергию, силу и страсть, оставляет незабываемое впечатление.",
    img: "/assets/img/perfume/boadicea_dragon.webp",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440008",
    slug: "russian-oud",
    title: "Russian Oud",
    brand: "Areej le Dore",
    price: [28000, 50000],
    ml: [5, 10],
    season: "winter",
    gender: "unisex",
    description:
      "Russian Oud представляет собой роскошную композицию, в которой доминирует натуральный удовый аккорд. Аромат раскрывается нотами драгоценного агарового дерева, дополненными пряными специями и бальзамическими оттенками. В базе присутствуют землистые ноты, амбра и мускус, создающие глубокое и насыщенное звучание.",
    img: "/assets/img/perfume/Areej_le_Dore___Russian_Oud.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440009",
    slug: "chypre-du-nord",
    title: "Chypre du Nord",
    brand: "Bortnikoff",
    price: [16500, 29700],
    ml: [5, 10],
    season: "fall",
    gender: "unisex",
    description:
      "Chypre du Nord - это современная интерпретация классического шипрового аромата. В композиции гармонично переплетаются цитрусовые ноты бергамота, пачули, дубового мха и лабданума. Натуральные ингредиенты создают богатую, многогранную композицию с винтажным характером.",
    img: "/assets/img/perfume/Bortnikoff_Chypre_du_Nord.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440010",
    slug: "oud-maximus",
    title: "Oud Maximus",
    brand: "Bortnikoff",
    price: [19800, 35640],
    ml: [5, 10],
    season: "winter",
    gender: "unisex",
    description:
      "Oud Maximus - это глубокий и насыщенный аромат, построенный вокруг редких сортов удового масла. Композиция открывается пряными нотами, переходящими в сердце из дорогих сортов агарового дерева. База аромата содержит амбру, мускус и древесные ноты, создающие богатый шлейф.",
    img: "/assets/img/perfume/Bortnikoff_Oud_Maximus.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440011",
    slug: "loubicharmee",
    title: "Loubicharmee",
    brand: "Christian Louboutin",
    price: [12500, 22500],
    ml: [5, 10],
    season: "spring",
    gender: "female",
    description:
      "Loubicharmee - это элегантный цветочный аромат, воплощающий женственность и шарм. Композиция открывается свежими нотами, переходящими в букет белых цветов. В базе присутствуют теплые древесные аккорды и мускус, создающие утонченный и соблазнительный шлейф.",
    img: "/assets/img/perfume/Christian_Louboutin_Loubicharme.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440012",
    slug: "absolu-aventus",
    title: "Absolu Aventus",
    brand: "Creed",
    price: [21000, 37800],
    ml: [5, 10],
    season: "spring",
    gender: "male",
    description:
      "Absolu Aventus - это более насыщенная версия классического Aventus. Аромат сохраняет фирменное сочетание ананаса и д",
    img: "/assets/img/perfume/Creed_Aventus.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440013",
    slug: "pure-white-cologne",
    title: "Pure White Cologne Les Royales Exclusives",
    brand: "Creed",
    price: [19500, 35100],
    ml: [5, 10],
    season: "summer",
    gender: "unisex",
    description:
      "Pure White Cologne - это свежий и элегантный аромат из эксклюзивной коллекции Les Royales. Композиция открывается искрящимися цитрусовыми нотами, переходящими в сердце из белых цветов. База из белого мускуса и амбры создает чистое, прозрачное звучание.",
    img: "/assets/img/perfume/Creed_Pure_White_Cologne_Les_Royales_Exclusives.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440014",
    slug: "oud-ispahan",
    title: "Oud Ispahan",
    brand: "Dior",
    price: [15500, 27900],
    ml: [5, 10],
    season: "winter",
    gender: "unisex",
    description:
      "Oud Ispahan - это роскошный восточный аромат, построенный вокруг благородного удового дерева. Композиция сочетает розу, пачули и лабданум, создавая богатую и чувственную ауру. Шафран и сандаловое дерево добавляют глубину и теплоту этому изысканному аромату.",
    img: "/assets/img/perfume/Dior_Oud_Ispahan.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440015",
    slug: "velvet-dessert-oud",
    title: "Velvet Dessert Oud",
    brand: "Dolce Gabbana",
    price: [17800, 32040],
    ml: [5, 10],
    season: "fall",
    gender: "unisex",
    description:
      "Velvet Dessert Oud - это гурманский восточный аромат, сочетающий сладость десертных нот с глубиной удового дерева. Композиция открывается пряными специями, переходящими в сердце из ванили и удового дерева. База из амбры и мускуса создает теплый, обволакивающий шлейф.",
    img: "/assets/img/perfume/Dolce___Gabbana_Velvet_Dessert_Oud.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440016",
    slug: "outcast-blue",
    title: "Outcast Blue Extrait de Parfum",
    brand: "Ex Nihilo",
    price: [14200, 25560],
    ml: [5, 10],
    season: "spring",
    gender: "unisex",
    description:
      "Outcast Blue - это свежий и современный аромат с морским характером. Композиция сочетает акватические ноты с пряными специями и древесными аккордами. Амбра и мускус в базе создают элегантный и стойкий шлейф, придавая аромату глубину и характер.",
    img: "/assets/img/perfume/Ex_Nihilo_Outcast_Blue_Extrait_de_Parfum.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440017",
    slug: "cannabis-intense",
    title: "Cannabis Intense",
    brand: "Fragrance du Bois",
    price: [13800, 24840],
    ml: [5, 10],
    season: "fall",
    gender: "unisex",
    description:
      "Cannabis Intense - это провокационный аромат, построенный вокруг зеленых и древесных нот. В композиции переплетаются пряные специи, землистые оттенки пачули и теплые древесные ноты. База из мускуса и амбры создает чувственный, обволакивающий шлейф.",
    img: "/assets/img/perfume/Fragrance_du_Bois_Cannabis_Intense.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440018",
    slug: "the-voice-of-the-snake",
    title: "The Voice of The Snake",
    brand: "Gucci",
    price: [16500, 29700],
    ml: [5, 10],
    season: "fall",
    gender: "unisex",
    description:
      "The Voice of The Snake - это гипнотический аромат, вдохновленный мистической змеей. Композиция открывается пряными нотами кардамона и перца, переходящими в сердце из кожи и древесных нот. База из амбры, мускуса и ванили создает таинственный и соблазнительный шлейф.",
    img: "/assets/img/perfume/Gucci_The_Voice_Of_The_Snake.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440019",
    slug: "musk-therapy",
    title: "Musk Therapy",
    brand: "INITIO",
    price: [14800, 26640],
    ml: [5, 10],
    season: "spring",
    gender: "unisex",
    description:
      "Musk Therapy - это чувственный аромат, построенный вокруг различных оттенков мускуса. В композиции сочетаются белый мускус, амбретта и животные ноты, создающие теплую и комфортную ауру. Ваниль и сандал в базе добавляют мягкость и глубину.",
    img: "/assets/img/perfume/INITIO_Musk_Therapy.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440020",
    slug: "oud-for-greatness",
    title: "Oud For Greatness",
    brand: "INITIO",
    price: [15200, 27360],
    ml: [5, 10],
    season: "winter",
    gender: "unisex",
    description:
      "Oud For Greatness - это величественный удовый аромат, воплощающий роскошь и силу. Композиция сочетает редкий уд с пряными специями и лавандой. В базе присутствуют мускус, пачули и древесные ноты, создающие богатый и стойкий шлейф.",
    img: "/assets/img/perfume/INITIO_Oud_For_Greatness.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440021",
    slug: "paragon",
    title: "Paragon",
    brand: "INITIO",
    price: [13900, 25020],
    ml: [5, 10],
    season: "spring",
    gender: "unisex",
    description:
      "Paragon - это свежий и элегантный аромат, олицетворяющий совершенство. В верхних нотах звучит бергамот и специи, переходящие в сердце из лаванды и древесных нот. База из амбры и мускуса создает утонченный и благородный шлейф.",
    img: "/assets/img/perfume/INITIO_Paragon.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440022",
    slug: "dark-lord",
    title: "Dark Lord",
    brand: "Kilian",
    price: [18500, 33300],
    ml: [5, 10],
    season: "winter",
    gender: "male",
    description:
      "Dark Lord - это темный и харизматичный аромат, воплощающий силу и мистику. Композиция открывается нотами рома и специй, переходящими в сердце из кожи и ветивера. База из черной амбры и удового дерева создает загадочный и притягательный шлейф.",
    img: "/assets/img/perfume/Kilian_Dark_Lord.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440023",
    slug: "straight-to-heaven-white-cristal",
    title: "Straight to Heaven White Cristal",
    brand: "Kilian",
    price: [17900, 32220],
    ml: [5, 10],
    season: "winter",
    gender: "unisex",
    description:
      "Straight to Heaven White Cristal - это роскошная версия классического аромата. В композиции доминируют ноты рома и ванили, дополненные пачули и белым мускусом. Древесные ноты кедра создают изысканный и соблазнительный шлейф.",
    img: "/assets/img/perfume/Kilian_Straight_to_Heaven_White_Cristal.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440024",
    slug: "baccarat-rouge-540-extrait",
    title: "Baccarat Rouge 540 Extrait",
    brand: "Maison Francis Kurkdjian",
    price: [22000, 39600],
    ml: [5, 10],
    season: "fall",
    gender: "unisex",
    description:
      "Baccarat Rouge 540 Extrait - это более концентрированная версия культового аромата. Яркое сочетание шафрана, жасмина и амбры создает узнаваемый signature-аромат. Древесные ноты и минеральная амбра формируют богатый, кристальный шлейф.",
    img: "/assets/img/perfume/Maison_Francis_Kurkdjian_Baccarat_Rouge_540_EXTRAIT.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440025",
    slug: "oud-satin-mood-extrait",
    title: "Oud Satin Mood Extrait",
    brand: "Maison Francis Kurkdjian",
    price: [21500, 38700],
    ml: [5, 10],
    season: "winter",
    gender: "unisex",
    description:
      "Oud Satin Mood Extrait - это роскошный восточный аромат с шелковистым характером. Болгарская роза и фиалка переплетаются с удом и ванилью, создавая богатую и чувственную композицию. База из амбры и бензоина добавляет теплоту и глубину.",
    img: "/assets/img/perfume/Maison_Francis_Kurkdjian_Oud_Satin_Mood_Extrait_de_parfum.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440026",
    slug: "instant-crush",
    title: "Instant Crush",
    brand: "Mancera",
    price: [8900, 16020],
    ml: [5, 10],
    season: "fall",
    gender: "unisex",
    description:
      "Instant Crush - это яркий и притягательный аромат, вызывающий мгновенное влечение. Композиция сочетает пряный имбирь и шафран с цветочным сердцем из розы и амбры. База из ванили и белого мускуса создает теплый и соблазнительный шлейф.",
    img: "/assets/img/perfume/Mancera_Instant_Crush.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440027",
    slug: "red-tobacco",
    title: "Red Tobacco",
    brand: "Mancera",
    price: [8500, 15300],
    ml: [5, 10],
    season: "winter",
    gender: "unisex",
    description:
      "Red Tobacco - это насыщенный табачный аромат с пряным характером. Композиция открывается корицей и специями, переходящими в сердце из табака и уда. База из гваякового дерева, пачули и ванили создает богатый и стойкий шлейф.",
    img: "/assets/img/perfume/Mancera_Red_Tobacco.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440028",
    slug: "ganymede",
    title: "Ganymede",
    brand: "Marc-Antoine Barrois",
    price: [12500, 22500],
    ml: [5, 10],
    season: "spring",
    gender: "unisex",
    description:
      "Ganymede - это минеральный, кожаный аромат с футуристическим характером. В композиции сочетаются мандарин, фиалка и замша, создавая необычное космическое звучание. База из минеральных нот и амброксана формирует современный и элегантный шлейф.",
    img: "/assets/img/perfume/Marc_Antoine_Barrois_Ganymede.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440029",
    slug: "french-leather",
    title: "French Leather",
    brand: "Memo",
    price: [15800, 28440],
    ml: [5, 10],
    season: "fall",
    gender: "unisex",
    description:
      "French Leather - это элегантный кожаный аромат, воплощающий парижский шик. Композиция сочетает розовый перец и можжевельник с нотами кожи и замши. База из мускуса и ветивера создает изысканный и утонченный шлейф.",
    img: "/assets/img/perfume/Memo_French_Leather.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440030",
    slug: "ani",
    title: "Ani",
    brand: "Nishane",
    price: [11500, 20700],
    ml: [5, 10],
    season: "fall",
    gender: "unisex",
    description:
      "Ani - это пряный восточный аромат, вдохновленный древним армянским городом. В композиции переплетаются бергамот, имбирь и зеленые ноты с богатым сердцем из ванили и бензоина. База из сандала и мускуса создает теплый и уютный шлейф.",
    img: "/assets/img/perfume/Nishane_Ani.jpg",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440031",
    slug: "fan-your-flames",
    title: "Fan Your Flames",
    brand: "Nishane",
    price: [12000, 21600],
    ml: [5, 10],
    season: "winter",
    gender: "unisex",
    description:
      "Fan Your Flames - это страстный и пылкий аромат с дымными нотами. Композиция сочетает ром и кокос с табаком и специями. База из ванили и древесных нот создает яркий и запоминающийся шлейф.",
    img: "/assets/img/perfume/Nishane_Fan_Your_Flames.jpg",
  },
];

export const brands = [...new Set(perfumes.map((perfume) => perfume.brand))];
